In [4]:
import numpy as np
import pandas as pd

üìä **Carregar dados**

In [8]:
cars = pd.read_csv('/content/drive/MyDrive/Datasets/MineracÃßaÃÉo de Dados/car_price_prediction.csv')

üëÅÔ∏è **Visualiza√ß√£o das primeiras linhas**

In [9]:
cars.head()

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4

üìù **Descri√ß√£o das Vari√°veis (colunas)**

-  `ID`: Identificador do carro
-  `Price`: **Alvo**: Pre√ßo do carro
-  `Levy`: Taxa/Imposto sobre o carro
-  `Manufacturer`: Fabricante
-  `Model`: Modelo espec√≠fico do carro
-  `Prod. year`: Ano de fabrica√ß√£o
-  `Category`: Categoria do carro
-  `Leather interior`: Possui interior de couro Yes/No
-  `Fuel type`: Tipo de combust√≠vel
-  `Engine volume`: Volume do motor
-  `Mileage`: Quilometragem
-  `Cylinders`: N√∫mero de cilindros
-  `Gear box type`: Tipo de c√¢mbio
-  `Drive wheels`: Tra√ß√£o
-  `Doors`: N√∫mero de portas"
-  `Wheel`: Lado do volante Left/Right
-  `Color`: Cor do carro
-  `Airbags`: N√∫mero de airbags

üìä **Dimens√£o do Dataset: Registros e Vari√°veis**

*Nesta etapa, √© apresentada a quantidade total de registros (linhas) e vari√°veis (colunas).*

In [20]:
df_shape = cars.shape

print(f"Total de Registros: {df_shape[0]}")
print(f"Total de Vari√°veis: {df_shape[1]}")

Total de Registros: 19237
Total de Vari√°veis: 18

üîç **Verifica√ß√£o dos Tipos de Vari√°veis**

*Nesta etapa, s√£o verificados os tipos de dados de cada vari√°vel do dataset. Essa an√°lise √© √∫til para validar a estrutura dos dados e garantir que cada vari√°vel esteja no formato adequado para as pr√≥ximas etapas da an√°lise.*

In [12]:
cars.dtypes

ID                    int64
Price                 int64
Levy                 object
Manufacturer         object
Model                object
Prod. year            int64
Category             object
Leather interior     object
Fuel type            object
Engine volume        object
Mileage              object
Cylinders           float64
Gear box type        object
Drive wheels         object
Doors                object
Wheel                object
Color                object
Airbags               int64
dtype: object

**Classifica√ß√£o das vari√°veis e gera√ß√£o de tabela resumo**

*Nesta etapa, as vari√°veis do dataset foram classificadas em dois grupos principais: quantitativas (num√©ricas) e qualitativas (categ√≥ricas). Em seguida, foi gerada uma tabela resumo que apresenta, lado a lado, os nomes das vari√°veis conforme o tipo, facilitando a visualiza√ß√£o e an√°lise dos dados.*

In [13]:
import pandas as pd

# Fun√ß√£o para classificar vari√°veis
def classificar_variaveis(df):
    quantitativas = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
    qualitativas = df.select_dtypes(include=['object', 'category', 'bool']).columns.tolist()
    return quantitativas, qualitativas

In [14]:
def gerar_tabela_resumo(quantitativas, qualitativas):
    max_len = max(len(quantitativas), len(qualitativas))
    qnt_pad = quantitativas + [""] * (max_len - len(quantitativas))
    qlt_pad = qualitativas + [""] * (max_len - len(qualitativas))

    tabela = pd.DataFrame({
        "Vari√°veis Quantitativas": qnt_pad,
        "Vari√°veis Qualitativas": qlt_pad
    })
    return tabela

In [15]:
def exibir_dataset_classificado(nome_dataset, df):
    # Classifica√ß√£o
    quantitativas, qualitativas = classificar_variaveis(df)

    # T√≠tulo
    print(f"\nüìã Dataset: {nome_dataset}")

    # Tamanho
    print(f"\nüìä Total: {df.shape[0]} linhas e {df.shape[1]} colunas")

    # Listas
    print("\n‚ñ∂ Vari√°veis Quantitativas:", quantitativas)
    print("‚ñ∂ Vari√°veis Qualitativas:", qualitativas)

    # Tabela resumo
    tabela_resumo = gerar_tabela_resumo(quantitativas, qualitativas)
    print("\n\nüìã Tabela Resumo:")
    print(tabela_resumo)

In [16]:
exibir_dataset_classificado("Cars", cars)

üìã Dataset: Cars

üìä Total: 19237 linhas e 18 colunas

‚ñ∂ Vari√°veis Quantitativas: ['ID', 'Price', 'Prod. year', 'Cylinders', 'Airbags']
‚ñ∂ Vari√°veis Qualitativas: ['Levy', 'Manufacturer', 'Model', 'Category', 'Leather interior', 'Fuel type', 'Engine volume', 'Mileage', 'Gear box type', 'Drive wheels', 'Doors', 'Wheel', 'Color']


üìã Tabela Resumo:
   Vari√°veis Quantitativas Vari√°veis Qualitativas
0                       ID                   Levy
1                    Price           Manufacturer
2               Prod. year                  Model
3                Cylinders               Category
4                  Airbags       Leather interior
5                                       Fuel type
6                                   Engine volume
7                                         Mileage
8                                   Gear box type
9                                    Drive wheels
10                                          Doors
11                                          Wheel
12                                          Color

üìù **Observa√ß√£o Sobre a Classifica√ß√£o das Vari√°veis**


Embora a classifica√ß√£o autom√°tica das vari√°veis com base nos tipos de dados (int64, float64, object) seja √∫til como ponto de partida, ela n√£o √© suficiente para uma an√°lise precisa. Algumas vari√°veis que aparecem como object s√£o, na verdade, quantitativas disfar√ßadas, devido √† presen√ßa de s√≠mbolos, unidades ou valores inconsistentes.

Por exemplo:

Levy: representa um valor monet√°rio, mas cont√©m valores ausentes ou s√≠mbolos, exigindo limpeza antes da convers√£o para num√©rico.

Mileage: est√° como string com "km", mas representa uma medida cont√≠nua.

Doors: deveria ser num√©rica, mas est√° como texto, possivelmente por valores como '>5'.

‚úÖ **Classifica√ß√£o Real das Vari√°veis**

üî¢ Vari√°veis Quantitativas (Num√©ricas)

-  Price
-  Levy
-  Prod. year
-  Engine volume
-  Mileage
-  Cylinders
-  Airbags
-  Doors

üî† Vari√°veis Qualitativas (Categ√≥ricas)

-  ID
-  Manufacturer
-  Model
-  Category
-  Leather interior
-  Fuel type
-  Gear box type
-  Drive wheels
-  Wheel
-  Color